% Script to get state anxiety VAS measures at each time point


group_prefixes = {...
    '..\..\DATA\2024\raw\Safe_first\data_exp_156254-v16\data_exp_156254-v16';
    '..\..\DATA\2024\raw\Threat_first\data_exp_170385-v4\data_exp_170385-v4';
    '..\..\DATA\2025\raw\safe_first\data_exp_156254-v17';
    '..\..\DATA\2025\raw\threat_first\data_exp_170385-v5'};

group_IDs = {'A', 'B', 'C', 'D'};

processed_tables = cell(4,1);

for iGroup = 1:4
    % experiment begin
    v1 = readtable([group_prefixes{iGroup}, '_task-11xj.csv']);
    
    % Post scream-rate
    v2 = readtable([group_prefixes{iGroup}, '_task-dkx5.csv']);
    
    % Safe-begin:
    v3 = readtable([group_prefixes{iGroup}, '_task-na2a.csv']);
    
    % Threat-begin:
    v4 = readtable([group_prefixes{iGroup}, '_task-p4ov.csv']);
    
    % Post threat
    v5 = readtable([group_prefixes{iGroup}, '_task-jhgs.csv']);
    
    % Preallocate space
    IDs = unique(v1.ParticipantPrivateID(~isnan(v1.ParticipantPrivateID)));
    
    group_table = table(...
        'Size', [numel(IDs), 7],...
        'VariableNames', {...
            'ID',...
            'Group',...
            'expt_start',...
            'post_ratings',...
            'pre_safe',...
            'pre_threat',...
            'post_threat'},...
        'VariableTypes', {...
            'doublenan',...
            'string',...
            'doublenan',...
            'doublenan',...
            'doublenan',...
            'doublenan',...
            'doublenan'}...
        );
    
    
    % Loop through IDs
    for iID = 1:numel(IDs)
        ID = IDs(iID);
        fprintf('\nID: %i', ID);
        group_table(iID, 'ID') = {ID};
        group_table(iID, 'Group') = {group_IDs{iGroup}};
    
        % Experiment begin
        group_table(iID, 'expt_start') = v1(...
            v1.ParticipantPrivateID == ID & ...
            strcmp(v1.ZoneType, 'response_slider_endValue'),...
            'Response');
    
        % Post ratings
        group_table(iID, 'post_ratings') = v2(...
            v2.ParticipantPrivateID == ID & ...
            strcmp(v2.ZoneType, 'response_slider_endValue'),...
            'Response');
    
        % Pre safe
        group_table(iID, 'pre_safe') = {str2double(v3(...
            v3.ParticipantPrivateID == ID & ...
            strcmp(v3.ZoneType, 'response_slider_endValue'),...
            'Response').Response)};
        
        % Pre threat
        group_table(iID, 'pre_threat') = {str2double(v4(...
            v4.ParticipantPrivateID == ID & ...
            strcmp(v4.ZoneType, 'response_slider_endValue'),...
            'Response').Response)};
    
        % Post threat
        group_table(iID, 'post_threat') = v5(...
            v5.ParticipantPrivateID == ID & ...
            strcmp(v5.ZoneType, 'response_slider_endValue'),...
            'Response');
    end

    processed_tables{iGroup} = group_table;

end

VAS_table = [processed_tables{1}; processed_tables{2}; processed_tables{3}; processed_tables{4}];

writetable(VAS_table, '..\..\DATA\state_anxiety_VAS.csv');




